name: deploy-auth

on: 
  push:
    branches: 
      - master
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t bishal69/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secret.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secret.DOCKER_PASSWORD }}
      - run: docker push bishal69/auth
